[package]
name = "rusty-fixer-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "3.0.0"
indicatif = "0.18.0"
clap = { version = "4.5", features = ["derive"] }

tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.24.0"
url = "2.5.2"